Support remote docker
greenplum-db/plcontainer pull request #630
Opened 2022-05-12 10:11 UTC by Sasasu

## Description

## Tests

## Additional Notes

## User Story or Issue

2022-05-17 07:39 UTC, beeender commented on src/plc_configuration.c
> +	backendConnectionInfo *r = palloc0(sizeof(runtimeConfEntry));
wrong type.
`sizeof(runtimeConfEntry)` -> `sizeof(backendConnectionInfo)`

2022-05-17 07:39 UTC, beeender commented on src/plc_configuration.c
> +	backendConnectionInfo *info = palloc0(sizeof(runtimeConfEntry));
ditto

2022-05-17 07:39 UTC, beeender commented on src/plc_configuration.c
> +		case PLC_BACKEND_UNIMPLEMENT:
and default case. won't the complier report warning?

2022-05-17 07:39 UTC, beeender commented on src/plc_configuration.c
> +			break;
default case

2022-05-17 07:45 UTC, Sasasu commented on src/plc_configuration.c
> +		case PLC_BACKEND_UNIMPLEMENT:
PLC_BACKEND_* is an enum. if list all possible variables in the case stmt, there is no compiler error.

2022-05-17 08:41 UTC, beeender commented on src/plc_process_api.c
> +    bool has_error = generate_sharing_options_and_uds_address(conf, backend, container_slot, connection, &volumeShare);
indent before `bool`

2022-05-17 08:55 UTC, Sasasu commented on src/plc_configuration.c
> +	backendConnectionInfo *info = palloc0(sizeof(runtimeConfEntry));
call stack:
> exec_simple_query()
> start_backend()
> runtime_conf_get_backend_connection_info()

so in runtime_conf_get_backend_connection_info need use CurrentMemoryContext.
but in config parser or client side. need to use PLy_malloc() to alloc memory in TopMemoryContext.

This is a bad API design but comes from the very beginning. just follow it :(

2022-05-19 03:26 UTC, Sasasu commented
sync with upstream. no logic change.

2022-06-02 07:49 UTC, beeender reviewed
LGTM
We need some tests to merge this. Let me finish the docker-in-docker thing then discuss how do we test this.
Also, the segments <-> container mapping is worth some discussion, but we can implement it in another PR.


To myself @beeender, you did a careful review on 412fa1b662

2022-06-02 07:49 UTC, beeender commented on src/containers.c
> +		plc_elog(LOG, "Backend delete error: %s", backend_error_message);
indent is wrong

2022-06-02 07:49 UTC, beeender commented on src/plc_backend_api.h
> +typedef int (*PLC_FPTR_create)(
The new APIs look nicer :+1:

2022-06-02 07:49 UTC, beeender commented on src/plc_configuration.h
> +#define pfree_null(x) do { if (x) pfree(x); } while(0)
minor: this can be moved to `plc_configuration.c`

2022-06-02 07:49 UTC, beeender commented on src/plc_docker_api.c
> +	         connection->tag == PLC_RUNTIME_CONNECTION_TCP ? "true" : "false", // .Env.useContainerNetwork
Would you please remind me again why this is relevant to the `useContainerNetwork`?

2022-06-02 07:49 UTC, beeender commented on src/plc_configuration.c
> +static void free_runtime_backend_entry(plcBackend *entry, bool release_self);
Will `release_self` ever be `true`? It doesn't seem to be needed

2022-06-02 07:49 UTC, beeender commented on src/plc_configuration.c
> +static plcBackend *runtime_backend_table = NULL;
Add a one-line comment to say the `[0]` is the default. It needs some time to figure it out by reading the code.

2022-06-29 03:41 UTC, Sasasu commented on src/containers.c
> +err:
XD

2022-06-29 03:49 UTC, Sasasu commented on src/plc_docker_api.c
> +	         connection->tag == PLC_RUNTIME_CONNECTION_TCP ? "true" : "false", // .Env.useContainerNetwork
`.Env.useContainerNetwork` is a environment variable inside container.
if useContainerNetwork = true. the pl client will open a TCP port and try to communicate with server using TCP/IP.

so PLC_RUNTIME_CONNECTION_TCP = useContainerNetwork.

useContainerNetwork is a bad name, has no relation to the network in container.

2022-06-29 03:53 UTC, Sasasu commented on src/plc_configuration.c
> +static void free_runtime_backend_entry(plcBackend *entry, bool release_self);
`free_runtime_conf_entry()` will `free(conf->anything)` then `free(conf)`
but runtime_backend alloced from a array. can not free only one element by this API.

I want the API looks like other free _* API :>

2023-03-20 06:46 UTC, RMTT commented on src/plc_configuration.c
> +	void *new_mem = MemoryContextAllocZero(TopMemoryContext, new_size);
Use `PLy_malloc` for consistency?

2023-03-21 02:23 UTC, Sasasu commented on src/containers.c
> +			if (check_container_if_oomkilled(backend, connection) == 1) {
there is a `sleep(3)` in `check_container_if_oomkilled`, I think the duplicate HTTP is on purpose. the interval of the tow request is 3s.

2023-03-21 02:24 UTC, Sasasu commented on src/containers.c
> +			if (check_container_if_oomkilled(backend, connection) == 1) {
anyway, if the modify can pass the test can not introduce any flaky case will be great.

2023-03-21 02:30 UTC, Sasasu commented on src/plc_configuration.c
> +	void *new_mem = MemoryContextAllocZero(TopMemoryContext, new_size);
I am not sure if it will work without the `memset(prt, 0, sizeof)`. cstring needs a NULL termination.
( and I don't like `PLy_malloc` this is a simple wrapper for a simple API

2023-03-21 02:50 UTC, Sasasu commented
I forget why remove the `useContainerNetwork`

the rebased branch here https://github.com/greenplum-db/plcontainer/tree/sa/b

2023-03-21 07:12 UTC, RMTT commented on src/plc_configuration.c
> +	void *new_mem = MemoryContextAllocZero(TopMemoryContext, new_size);
But it already existed, so i think we can use it for consistency.

2023-07-14 06:07 UTC, beeender requested changes
1. `make installcheck` crashes:

```
warning: Section `.reg-xstate/244217' in core file too small.
#0  0x00007f2ac5a9f26c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f2ac5a9f26c in ?? () from /usr/lib/libc.so.6
#1  0x00007f2ac5a4fa08 in raise () from /usr/lib/libc.so.6
#2  0x000055924ed8e558 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=0x55924f4aca00 "Segment process",
    postgres_signal_arg=11) at elog.c:5640
#3  0x000055924ebc982c in CdbProgramErrorHandler (postgres_signal_arg=11) at postgres.c:3583
#4  <signal handler called>
#5  0x00007f2ac5b6f85d in ?? () from /usr/lib/libc.so.6
#6  0x00007f2ab1190996 in plc_docker_inspect_container (type=PLC_INSPECT_STATUS, backend=0x55925593b170,
    connection=0x55925593a258, element=0x7ffcba435b50) at /home/cc/repo/plcontainer/src/plc_docker_api.c:608
#7  0x00007f2ab1187663 in plc_backend_inspect (type=PLC_INSPECT_STATUS, backend=0x55925593b170, connection=0x55925593a258,
    element=0x7ffcba435b50) at /home/cc/repo/plcontainer/src/plc_backend_api.c:98
#8  0x00007f2ab1184568 in delete_backend_if_exited (backend=0x55925593b170, connection=0x55925593a258)
    at /home/cc/repo/plcontainer/src/containers.c:97
#9  0x00007f2ab1185842 in delete_containers () at /home/cc/repo/plcontainer/src/containers.c:567
#10 0x00007f2ab1194142 in plcontainer_cleanup (code=0, arg=0) at /home/cc/repo/plcontainer/src/plcontainer.c:107
#11 0x000055924eb8eca9 in proc_exit_prepare (code=0) at ipc.c:229
#12 0x000055924eb8eaf2 in proc_exit (code=0) at ipc.c:104
#13 0x000055924ebcc774 in PostgresMain (argc=1, argv=0x559255812a68, dbname=0x559255812940 "testr",
    username=0x5592557dd0f8 "cc") at postgres.c:5758
#14 0x000055924eb1b9b1 in BackendRun (port=0x55925580cfa0) at postmaster.c:4816
#15 0x000055924eb1ac8c in BackendStartup (port=0x55925580cfa0) at postmaster.c:4480
#16 0x000055924eb19ac4 in ServerLoop () at postmaster.c:1945
#17 0x000055924eb171ed in PostmasterMain (argc=5, argv=0x5592557dae60) at postmaster.c:1515
#18 0x000055924e9e060d in main (argc=5, argv=0x5592557dae60) at main.c:245
(gdb) f 6
#6  0x00007f2ab1190996 in plc_docker_inspect_container (type=PLC_INSPECT_STATUS, backend=0x55925593b170,
    connection=0x55925593a258, element=0x7ffcba435b50) at /home/cc/repo/plcontainer/src/plc_docker_api.c:608
608             url = palloc(strlen(method) + strlen(connection->identity) + 2);
(gdb) p method
$1 = 0x7f2ab12e28a5 "/containers/%s/json"
(gdb) p connection->identity
$2 = 0x7f7f7f7f7f7f7f7f <error: Cannot access memory at address 0x7f7f7f7f7f7f7f7f>
(gdb)
```

2. Some tests are needed before merging. Create a new regress test file like `remote_container.sql`. And it is possible to enable the remote access on CI by changing https://github.com/greenplum-db/plcontainer/blob/main/concourse/scripts/docker-lib.sh

2023-07-14 06:43 UTC, beeender commented
It migth be caused by the fact that I didn't do `plcontainer runtime-add`, but it should not crash like this.

2023-09-14 07:21 UTC, beeender commented on src/plc_configuration.c
> -
Removing line 852-855 will result in less code. But this is OK.

2023-09-25 02:18 UTC, beeender approved these changes

2023-10-10 07:18 UTC, merged