[WIP] Make PL/Container compatible with Greenplum 7.
greenplum-db/plcontainer pull request #665
Opened 2023-01-06 04:24 UTC by higuoxing

I will add description once I finish this patch.

2023-01-17 02:52 UTC, beeender commented on concourse/pipeline/job_def.lib.yml
> +res_test_image: rocky8-gpdb7-image-test
Can we test the rocky8 build for both `rhel8` and `rocky8` like what have been done for ip4r? See https://github.com/pivotal/ip4r/pull/7

2023-01-17 02:52 UTC, beeender commented on concourse/pipeline/res_def.yml
> +    uri: https://github.com/higuoxing/plcontainer
hmmmmmm ... interesting .....

2023-01-17 02:52 UTC, beeender commented on management/bin/plcontainer
> +        from gppylib.commands.unix import Scp as Rsync
add some comments. This could be confusing who is not familiar with pylib for gp6&7

2023-01-17 08:29 UTC, beeender reviewed
Haven't check the tests yet.

2023-01-17 08:29 UTC, beeender commented on concourse/pipeline/res_def.yml
> +    repository: gcr.io/data-gpdb-private-images/gpdb7-rhel8-test
`gpdb7-rhel8-test` -> `gpdb7-rhel8-build`

2023-01-17 08:29 UTC, beeender commented on concourse/pipeline/res_def.yml
> +- name: bin_plcontainer_gpdb7_rhel8_release
remove this? we only do `rocky8` release.

2023-01-17 08:29 UTC, beeender commented on concourse/scripts/test_plcontainer.sh
> +    createdb contrib_regression || true
"metadata query" what is that? Why didn't we need it before?

2023-01-17 08:29 UTC, beeender commented on tests/isolation2/Makefile
> +	$(top_builddir)/src/test/regress/pg_isolation2_regress --init-file=../init_file --inputdir=$(srcdir) --dbname=isolation2resgrouptest --schedule=isolation2_resgroup_schedule
I thought this file is not needed, why didn't I delete this? Nevermind, I will delete this later.

2023-01-17 08:29 UTC, beeender commented on src/plc_container_info.c
> +	LWLockInitialize(plc_lw_lock, LWLockNewTrancheId());
This same API exists on GPDB6 as well. Don't we need it for both?

2023-01-17 08:32 UTC, Sasasu commented on concourse/scripts/test_plcontainer.sh
> +    createdb contrib_regression || true
src/test/regress will create the `contrib_regression` database in gpdb6

2023-01-17 14:14 UTC, RMTT requested changes

2023-01-17 14:14 UTC, RMTT commented on src/common/comm_connectivity.c
> +		int saved_errno = errno;
Just curious, why need `saved_errno`?

2023-01-18 09:50 UTC, RMTT approved these changes
LGTM

2023-01-19 01:04 UTC, higuoxing commented on tests/isolation2/Makefile
> +	$(top_builddir)/src/test/regress/pg_isolation2_regress --init-file=../init_file --inputdir=$(srcdir) --dbname=isolation2resgrouptest --schedule=isolation2_resgroup_schedule
Which file? `Makefile`?

2023-01-30 02:20 UTC, merged