Sa/removedockertools
greenplum-db/plcontainer pull request #703
Opened 2023-11-15 09:39 UTC by Sasasu

```
./management/bin/plcontainer remote-setup -h
usage: plcontainer remote-setup [-h] --hosts HOSTS [--clientdir CLIENTDIR]

optional arguments:
  -h, --help            show this help message and exit
  --hosts HOSTS         a list of remote host IP (e.g. '128.66.0.1,128.66.0.2') or a gpscp hostfile
  --clientdir CLIENTDIR
                        the dir to save plcontainer language client
```

testing

2023-11-16 07:50 UTC, Sasasu commented
ci https://dev2.ci.gpdb.pivotal.io/teams/gp-extensions/pipelines/dev.plcontainer.sa_removedockertools.sa

2023-11-16 08:03 UTC, RMTT commented on management/bin/plcontainer
> +        clientdir = os.path.dirname(clientdir)
Can use `PLCONTAINER_CLIENT_DIR/*` for both?

2023-11-16 08:05 UTC, RMTT commented on management/bin/plcontainer
> +        raise ex
What the difference between `raise ex` and `raise(ex)`

2023-11-16 08:49 UTC, Sasasu commented on management/bin/plcontainer
> +        raise ex
no different.
raise is a keyword not a function. `()` equals to nothing

```

In [7]: ast.dump(ast.parse('raise 1'))
Out[7]: 'Module(body=[Raise(exc=Constant(value=1))], type_ignores=[])'

In [8]: ast.dump(ast.parse('raise()'))
Out[8]: 'Module(body=[Raise(exc=Tuple(elts=[], ctx=Load()))], type_ignores=[])'

In [9]: ast.dump(ast.parse('raise(1)'))
Out[9]: 'Module(body=[Raise(exc=Constant(value=1))], type_ignores=[])'

In [10]: ast.dump(ast.parse('raise(1,)'))
Out[10]: 'Module(body=[Raise(exc=Tuple(elts=[Constant(value=1)], ctx=Load()))], type_ignores=[])'
```

2023-11-16 13:56 UTC, Sasasu commented
one squashed commit. 6878ae1d58fbeb2307b75e0dbc87f421bfa6852e
use `PLCONTAINER_CLIENT_DIR/*` for both rsync and scp

2023-11-17 02:04 UTC, RMTT requested changes

2023-11-17 02:04 UTC, RMTT commented on tests/regress/expected/test_configuration.out
> +\! docker ps -a
i think the output is unnecessary.

2023-11-17 02:04 UTC, RMTT commented on tests/regress/expected/test_configuration.out
> +-- start_ignore
i think the output is unnecessary.

2023-11-17 07:00 UTC, Sasasu commented on tests/regress/expected/test_configuration.out
> +-- start_ignore
this is some debug message to explain why `count(*) from plcontainer_containers_summary()`  returns `1`.
keep this message can show what happened in the design time. in this case, there are many running container but only one is belong to dbid=self.

and this file is copied from `tests/regress/result/`. remove those lines need to edit the output by hand.

2023-11-17 07:00 UTC, Sasasu commented on tests/regress/expected/test_configuration.out
> +\! docker ps -a
this is some debug message to explain why count(*) from plcontainer_containers_summary() returns 1.
keep this message can show what happened in the design time. in this case, there are many running container but only one is belong to dbid=self.

and this file is copied from tests/regress/result/. remove those lines need to edit the output by hand.

2023-11-20 01:58 UTC, RMTT approved these changes

2023-11-20 08:05 UTC, merged